base:
  project : "Salary_Prediction"
  random_state: 42
  target: avg_salary

data_source:
  gdrive_source: Scrape_zone/job_listings.csv

load_data:
  raw_data_csv: data/raw/listings.csv

cleaned_data:
  cleaned_data_csv: data/cleaned/final_data.csv

EDA_data:
  eda_data_csv: data/eda/eda_data.csv

split_data: 
  train_path: data/processed/train.csv
  test_path: data/processed/test.csv
  test_size: 0.2

estimators:
  RandomForest:
    params:
      criterion: 'mae'
      n_estimators: 220
     

model_dir: saved_models

report:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction/model/model.joblib